/**
 * Tests for app/layout.tsx
 *
 * RootLayout is a React Server Component. It renders the HTML skeleton
 * (<html> + <body>) and injects Google Font CSS custom properties.
 * next/font/google is mocked because it performs network I/O and is not
 * available in the jsdom test environment.
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen } from '@testing-library/react';

// ---------------------------------------------------------------------------
// Mocks
// ---------------------------------------------------------------------------

// next/font/google makes real network requests and returns objects whose
// `variable` and `className` values depend on font-loading infrastructure
// that is unavailable in jsdom. We replace each font constructor with a
// factory that returns deterministic values.
vi.mock('next/font/google', () => ({
  Geist: vi.fn(() => ({
    variable: '--font-geist-sans',
    className: 'geist-sans',
  })),
  Geist_Mono: vi.fn(() => ({
    variable: '--font-geist-mono',
    className: 'geist-mono',
  })),
}));

// globals.css is a side-effect import with no JS surface — suppress it.
vi.mock('./globals.css', () => ({}));

// ---------------------------------------------------------------------------
// Import the module under test AFTER mocks are registered.
// ---------------------------------------------------------------------------
import RootLayout, { metadata } from './layout';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function renderLayout(children: React.ReactNode) {
  // RootLayout returns an <html> element. React Testing Library mounts into
  // document.body by default; wrapping in a plain container keeps the test
  // renderer happy while still exercising the real component tree.
  return render(<RootLayout>{children}</RootLayout>);
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('RootLayout', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe('metadata export', () => {
    it('exports a metadata object', () => {
      expect(metadata).toBeDefined();
      expect(typeof metadata).toBe('object');
    });

    it('has the expected title', () => {
      expect(metadata.title).toBe('Create Next App');
    });

    it('has the expected description', () => {
      expect(metadata.description).toBe('Generated by create next app');
    });
  });

  describe('happy path — rendering', () => {
    it('renders children inside the body', () => {
      renderLayout(<p>Hello world</p>);
      expect(screen.getByText('Hello world')).toBeInTheDocument();
    });

    it('renders multiple children', () => {
      renderLayout(
        <>
          <span>First</span>
          <span>Second</span>
        </>
      );
      expect(screen.getByText('First')).toBeInTheDocument();
      expect(screen.getByText('Second')).toBeInTheDocument();
    });

    it('injects geist-sans font CSS variable onto the html element', () => {
      const { container } = renderLayout(<div />);
      // The <html> element is the first element in the rendered output.
      const html = container.closest('html') ?? container.firstElementChild;
      expect(html?.className).toContain('--font-geist-sans');
    });

    it('injects geist-mono font CSS variable onto the html element', () => {
      const { container } = renderLayout(<div />);
      const html = container.closest('html') ?? container.firstElementChild;
      expect(html?.className).toContain('--font-geist-mono');
    });

    it('sets lang="en" on the html element', () => {
      const { container } = renderLayout(<div />);
      const html = container.closest('html') ?? container.firstElementChild;
      expect(html).toHaveAttribute('lang', 'en');
    });
  });

  describe('edge cases', () => {
    it('renders when children is null', () => {
      // Should not throw; body may be empty but the layout still mounts.
      expect(() => renderLayout(null)).not.toThrow();
    });

    it('renders when children is an empty string', () => {
      expect(() => renderLayout('')).not.toThrow();
    });

    it('renders when children is a deeply nested tree', () => {
      renderLayout(
        <div>
          <section>
            <article>
              <p>Deep content</p>
            </article>
          </section>
        </div>
      );
      expect(screen.getByText('Deep content')).toBeInTheDocument();
    });

    it('renders text-only children without a wrapper element', () => {
      renderLayout('plain text child');
      expect(screen.getByText('plain text child')).toBeInTheDocument();
    });
  });
});
